<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Animal;

class AnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            // ==========================================
            // ECOSISTEMA 1: SABANA (ID: 1 y 2)
            // ==========================================
            ['zone_id' => 1, 'common_name' => 'León', 'species' => 'Panthera leo', 'birth_date' => '2015-05-12', 'diet' => 'Carnívoro', 'curiosity' => 'Su impresionante rugido puede escucharse hasta 9 kilómetros de distancia para marcar territorio.', 'image' => 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=500'],
            ['zone_id' => 1, 'common_name' => 'Elefante asiático', 'species' => 'Elephas maximus', 'birth_date' => '2008-11-20', 'diet' => 'Herbívoro', 'curiosity' => 'Son capaces de sentir emociones profundas y reconocerse en espejos, demostrando autoconciencia.', 'image' => 'https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?w=500'],
            ['zone_id' => 1, 'common_name' => 'Jirafa', 'species' => 'Giraffa camelopardalis', 'birth_date' => '2012-09-30', 'diet' => 'Herbívoro', 'curiosity' => 'Tienen una lengua azul oscuro de 50 cm con la cual pueden comer espinas sin dañarse.', 'image' => 'https://images.unsplash.com/photo-1577114995803-d8ce0e2b4aa9?w=500'],
            ['zone_id' => 1, 'common_name' => 'Cebra de llanura', 'species' => 'Equus quagga', 'birth_date' => '2017-03-15', 'diet' => 'Herbívoro', 'curiosity' => 'Las rayas de cada cebra son únicas, como las huellas dactilares humanas.', 'image' => 'https://images.unsplash.com/photo-1521111586551-7db13fc4e38c?w=500'],
            ['zone_id' => 1, 'common_name' => 'Guepardo', 'species' => 'Acinonyx jubatus', 'birth_date' => '2019-08-22', 'diet' => 'Carnívoro', 'curiosity' => 'Es el animal terrestre más rápido del mundo, capaz de alcanzar los 112 km/h en solo tres segundos.', 'image' => 'https://images.unsplash.com/photo-1534141695508-251f4961d154?w=500'],
            ['zone_id' => 1, 'common_name' => 'Rinoceronte blanco', 'species' => 'Ceratotherium simum', 'birth_date' => '2011-01-10', 'diet' => 'Herbívoro', 'curiosity' => 'A pesar de su nombre, no son blancos. El término viene de una mala traducción.', 'image' => 'https://images.unsplash.com/photo-1535940443424-c108153406e2?w=500'],
            ['zone_id' => 1, 'common_name' => 'Avestruz', 'species' => 'Struthio camelus', 'birth_date' => '2020-04-12', 'diet' => 'Omnívoro', 'curiosity' => 'Es el ave más grande y pesada del mundo. No puede volar, pero corre a 70 km/h.', 'image' => 'https://images.unsplash.com/photo-1549471013-3364d7220b75?w=500'],
            ['zone_id' => 1, 'common_name' => 'Suricata', 'species' => 'Suricata suricatta', 'birth_date' => '2022-01-05', 'diet' => 'Omnívoro', 'curiosity' => 'Son inmunes al veneno de muchas serpientes y escorpiones mortales de los que se alimentan.', 'image' => 'https://images.unsplash.com/photo-1541280910158-c4e14f9a0c1f?w=500'],
            ['zone_id' => 1, 'common_name' => 'Hiena moteada', 'species' => 'Crocuta crocuta', 'birth_date' => '2018-11-30', 'diet' => 'Carnívoro', 'curiosity' => 'Tienen una de las mandíbulas más fuertes del reino animal.', 'image' => 'https://images.unsplash.com/photo-1596708304910-a29241b777a8?w=500'],
            ['zone_id' => 1, 'common_name' => 'Búfalo del Cabo', 'species' => 'Syncerus caffer', 'birth_date' => '2016-07-22', 'diet' => 'Herbívoro', 'curiosity' => 'Es uno de los animales más temidos de África, conocido por tener una memoria excelente.', 'image' => 'https://images.unsplash.com/photo-1523456188358-86d7e002daab?w=500'],
            ['zone_id' => 1, 'common_name' => 'Ñu azul', 'species' => 'Connochaetes taurinus', 'birth_date' => '2018-09-12', 'diet' => 'Herbívoro', 'curiosity' => 'Protagonizan una de las migraciones más espectaculares del planeta.', 'image' => 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?w=500'],
            ['zone_id' => 1, 'common_name' => 'Babuino', 'species' => 'Papio cynocephalus', 'birth_date' => '2016-03-22', 'diet' => 'Omnívoro', 'curiosity' => 'Tienen una estructura social muy compleja y pueden comunicarse con más de 30 vocalizaciones distintas.', 'image' => 'https://images.unsplash.com/photo-1540149025987-16479e0a0a54?w=500'],
            ['zone_id' => 1, 'common_name' => 'Licaón (Perro salvaje)', 'species' => 'Lycaon pictus', 'birth_date' => '2020-11-15', 'diet' => 'Carnívoro', 'curiosity' => 'Son los cazadores más letales de África. Su tasa de éxito en la caza es del 80%.', 'image' => 'https://images.unsplash.com/photo-1580414594220-410a563db58a?w=500'],
            ['zone_id' => 1, 'common_name' => 'Oryx', 'species' => 'Oryx gazella', 'birth_date' => '2017-06-30', 'diet' => 'Herbívoro', 'curiosity' => 'Pueden sobrevivir semanas sin beber agua.', 'image' => 'https://images.unsplash.com/photo-1517332219491-b7553b98c564?w=500'],
            ['zone_id' => 1, 'common_name' => 'Facóquero', 'species' => 'Phacochoerus africanus', 'birth_date' => '2019-01-14', 'diet' => 'Omnívoro', 'curiosity' => 'Suelen huir de los depredadores corriendo a 50 km/h con la cola levantada como una antena.', 'image' => 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=500'],

            // ZONA ACUÁTICA
            ['zone_id' => 2, 'common_name' => 'Cocodrilo', 'species' => 'Crocodylidae', 'birth_date' => '2010-02-14', 'diet' => 'Carnívoro', 'curiosity' => 'Su mordida equivale a 27 veces la fuerza humana.', 'image' => 'https://images.unsplash.com/photo-1595433409683-943ded8e7b1d?w=500'],
            ['zone_id' => 2, 'common_name' => 'Hipopótamo', 'species' => 'Hippopotamus amphibius', 'birth_date' => '2014-04-18', 'diet' => 'Herbívoro', 'curiosity' => 'Segregan un líquido rojo que actúa como protector solar natural.', 'image' => 'https://images.unsplash.com/photo-1604454112929-42dedc7c8424?w=500'],
            ['zone_id' => 2, 'common_name' => 'Flamenco común', 'species' => 'Phoenicopterus roseus', 'birth_date' => '2020-06-05', 'diet' => 'Omnívoro', 'curiosity' => 'Nacen con el plumaje gris. Su color rosa proviene de los crustáceos que comen.', 'image' => 'https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=500'],
            ['zone_id' => 2, 'common_name' => 'Capibara', 'species' => 'Hydrochoerus hydrochaeris', 'birth_date' => '2021-09-12', 'diet' => 'Herbívoro', 'curiosity' => 'Es el roedor más grande del mundo y un excelente nadador.', 'image' => 'https://images.unsplash.com/photo-1588631168925-fb3912bf28a8?w=500'],
            ['zone_id' => 2, 'common_name' => 'Pelícano blanco', 'species' => 'Pelecanus onocrotalus', 'birth_date' => '2019-03-08', 'diet' => 'Piscívoro', 'curiosity' => 'La bolsa de su pico puede contener hasta 13 litros de agua.', 'image' => 'https://images.unsplash.com/photo-1507661502690-3a5ce39b4662?w=500'],
            ['zone_id' => 2, 'common_name' => 'Picozapato', 'species' => 'Balaeniceps rex', 'birth_date' => '2015-08-08', 'diet' => 'Carnívoro', 'curiosity' => 'Suelen quedarse completamente inmóviles durante horas para cazar.', 'image' => 'https://images.unsplash.com/photo-1615039322238-34850c9c73bf?w=500'],
            ['zone_id' => 2, 'common_name' => 'Varano del Nilo', 'species' => 'Varanus niloticus', 'birth_date' => '2021-04-10', 'diet' => 'Carnívoro', 'curiosity' => 'Son reptiles extremadamente inteligentes y ágiles.', 'image' => 'https://images.unsplash.com/photo-1560020786-896dbec8e1fb?w=500'],
            ['zone_id' => 2, 'common_name' => 'Cobo de agua', 'species' => 'Kobus ellipsiprymnus', 'birth_date' => '2018-12-05', 'diet' => 'Herbívoro', 'curiosity' => 'Tienen glándulas que segregan una sustancia aceitosa y maloliente que impermeabiliza su pelaje.', 'image' => 'https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?w=500'],
            ['zone_id' => 2, 'common_name' => 'Grulla coronada', 'species' => 'Balearica regulorum', 'birth_date' => '2022-02-28', 'diet' => 'Omnívoro', 'curiosity' => 'Es famosa por su cresta dorada y sus elaboradas danzas de cortejo.', 'image' => 'https://images.unsplash.com/photo-1555169062-013468b47731?w=500'],
            ['zone_id' => 2, 'common_name' => 'Águila pescadora', 'species' => 'Pandion haliaetus', 'birth_date' => '2019-07-17', 'diet' => 'Piscívoro', 'curiosity' => 'Sus garras tienen unas escamas ásperas especiales para sujetar peces resbaladizos.', 'image' => 'https://images.unsplash.com/photo-1590494050215-684a0d813727?w=500'],

            // ==========================================
            // ECOSISTEMA 2: JUNGLA - AVIARIO (Solo pájaros) (ID: 3)
            // ==========================================
            ['zone_id' => 3, 'common_name' => 'Tucán toco', 'species' => 'Ramphastos toco', 'birth_date' => '2021-04-11', 'diet' => 'Frugívoro', 'curiosity' => 'Su enorme pico no es un arma, le sirve como radiador para regular la temperatura.', 'image' => 'https://images.unsplash.com/photo-1549480662-8e10080644dd?w=500'],
            ['zone_id' => 3, 'common_name' => 'Guacamayo Rojo', 'species' => 'Ara macao', 'birth_date' => '2015-10-10', 'diet' => 'Frugívoro', 'curiosity' => 'Son aves monógamas que se emparejan de por vida.', 'image' => 'https://images.unsplash.com/photo-1541434389020-f1dbb1626353?w=500'],
            ['zone_id' => 3, 'common_name' => 'Guacamayo Azul y Amarillo', 'species' => 'Ara ararauna', 'birth_date' => '2020-01-20', 'diet' => 'Frugívoro', 'curiosity' => 'Tienen tanta fuerza en el pico que pueden romper la cáscara de un coco.', 'image' => 'https://images.unsplash.com/photo-1552054230-07e15f8386f7?w=500'],
            ['zone_id' => 3, 'common_name' => 'Cálao Rinoceronte', 'species' => 'Buceros rhinoceros', 'birth_date' => '2019-09-09', 'diet' => 'Omnívoro', 'curiosity' => 'Tienen una protuberancia en el pico llamada casco que amplifica sus cantos.', 'image' => 'https://images.unsplash.com/photo-1606132791402-4fc937cc57ea?w=500'],

            // ==========================================
            // ECOSISTEMA 2: JUNGLA - REPTILARIO (ID: 4)
            // ==========================================
            ['zone_id' => 4, 'common_name' => 'Víbora', 'species' => 'Viperinae', 'birth_date' => '2021-11-11', 'diet' => 'Carnívoro', 'curiosity' => 'Usan su lengua bífida para recolectar partículas y llevarlas al Órgano de Jacobson.', 'image' => 'https://images.unsplash.com/photo-1605051538177-72c289389de5?w=500'],
            ['zone_id' => 4, 'common_name' => 'Camaleón pantera', 'species' => 'Furcifer pardalis', 'birth_date' => '2022-03-08', 'diet' => 'Insectívoro', 'curiosity' => 'Tienen visión de 360 grados. Sus ojos pueden moverse de forma independiente.', 'image' => 'https://images.unsplash.com/photo-1541300613939-71366b37c92e?w=500'],
            ['zone_id' => 4, 'common_name' => 'Rana dardo venenosa', 'species' => 'Dendrobatidae', 'birth_date' => '2023-01-20', 'diet' => 'Insectívoro', 'curiosity' => 'En los zoológicos no son venenosas porque pierden su toxicidad por la dieta.', 'image' => 'https://images.unsplash.com/photo-1579895240409-f1fb525f0a71?w=500'],
            ['zone_id' => 4, 'common_name' => 'Anaconda verde', 'species' => 'Eunectes murinus', 'birth_date' => '2015-10-31', 'diet' => 'Carnívoro', 'curiosity' => 'Es la serpiente más pesada del mundo.', 'image' => 'https://images.unsplash.com/photo-1563234979-58ec78995a97?w=500'],
            ['zone_id' => 4, 'common_name' => 'Iguana Verde', 'species' => 'Iguana iguana', 'birth_date' => '2018-05-19', 'diet' => 'Herbívoro', 'curiosity' => 'Tienen un "tercer ojo" en la cabeza para detectar sombras.', 'image' => 'https://images.unsplash.com/photo-1517783999520-f068d7431a60?w=500'],
            ['zone_id' => 4, 'common_name' => 'Dragón de Komodo', 'species' => 'Varanus komodoensis', 'birth_date' => '2014-12-11', 'diet' => 'Carnívoro', 'curiosity' => 'Es el lagarto más grande del planeta.', 'image' => 'https://images.unsplash.com/photo-1582515082404-e3fb6f0c1dc4?w=500'],
            ['zone_id' => 4, 'common_name' => 'Boa constrictor', 'species' => 'Boa constrictor', 'birth_date' => '2017-06-25', 'diet' => 'Carnívoro', 'curiosity' => 'Matan a sus presas cortando el flujo sanguíneo con su abrazo.', 'image' => 'https://images.unsplash.com/photo-1502450849313-1628178a5e01?w=500'],
            ['zone_id' => 4, 'common_name' => 'Tortuga Gigante de Aldabra', 'species' => 'Aldabrachelys gigantea', 'birth_date' => '1950-01-01', 'diet' => 'Herbívoro', 'curiosity' => 'Pueden vivir más de 150 años.', 'image' => 'https://images.unsplash.com/photo-1521714088998-d7b56a31f79c?w=500'],
            ['zone_id' => 4, 'common_name' => 'Mamba Negra', 'species' => 'Dendroaspis polylepis', 'birth_date' => '2018-02-14', 'diet' => 'Carnívoro', 'curiosity' => 'Su nombre viene del interior de su boca, que es negro como la tinta.', 'image' => 'https://images.unsplash.com/photo-1533031023223-287711311b51?w=500'],
            ['zone_id' => 4, 'common_name' => 'Pitón Reticulada', 'species' => 'Malayopython reticulatus', 'birth_date' => '2011-07-22', 'diet' => 'Carnívoro', 'curiosity' => 'Es la serpiente más larga del mundo, pudiendo superar los 7 metros.', 'image' => 'https://images.unsplash.com/photo-1629858340773-89ea27303038?w=500'],
            ['zone_id' => 4, 'common_name' => 'Cobra Real', 'species' => 'Ophiophagus hannah', 'birth_date' => '2016-05-05', 'diet' => 'Carnívoro', 'curiosity' => 'Es la única serpiente del mundo que construye nidos para sus huevos.', 'image' => 'https://images.unsplash.com/photo-1608828036222-1d7010a30b42?w=500'],
            ['zone_id' => 4, 'common_name' => 'Gecko Diurno', 'species' => 'Phelsuma madagascariensis', 'birth_date' => '2022-10-10', 'diet' => 'Insectívoro', 'curiosity' => 'Para limpiar y humedecer sus grandes ojos, ¡los lamen con su larga lengua!', 'image' => 'https://images.unsplash.com/photo-1558237937-29d9e4313fa7?w=500'],
            ['zone_id' => 4, 'common_name' => 'Rana Arborícola Verde', 'species' => 'Litoria caerulea', 'birth_date' => '2023-01-15', 'diet' => 'Insectívoro', 'curiosity' => 'Sus dedos segregan un moco pegajoso que funciona como ventosa.', 'image' => 'https://images.unsplash.com/photo-1560235790-264624388e6e?w=500'],
            ['zone_id' => 4, 'common_name' => 'Caimán de Anteojos', 'species' => 'Caiman crocodilus', 'birth_date' => '2017-12-01', 'diet' => 'Carnívoro', 'curiosity' => 'Se le llama así por una cresta ósea entre sus ojos que parece unas gafas.', 'image' => 'https://images.unsplash.com/photo-1549449341-a1d275727191?w=500'],
            ['zone_id' => 4, 'common_name' => 'Basilisco Verde', 'species' => 'Basiliscus plumifrons', 'birth_date' => '2021-08-19', 'diet' => 'Omnívoro', 'curiosity' => 'Se le conoce como lagarto Jesucristo por correr sobre el agua sin hundirse.', 'image' => 'https://images.unsplash.com/photo-1506540194848-15467e4529db?w=500'],
            ['zone_id' => 4, 'common_name' => 'Monstruo de Gila', 'species' => 'Heloderma suspectum', 'birth_date' => '2015-06-11', 'diet' => 'Carnívoro', 'curiosity' => 'Es uno de los pocos lagartos venenosos del mundo.', 'image' => 'https://images.unsplash.com/photo-1627578272808-1c469273f324?w=500'],

            // ==========================================
            // ECOSISTEMA 2: JUNGLA - TREPADORES Y TERRESTRES (La nueva Zona ID: 5)
            // ==========================================
            ['zone_id' => 5, 'common_name' => 'Chimpancé', 'species' => 'Pan troglodytes', 'birth_date' => '2018-07-05', 'diet' => 'Omnívoro', 'curiosity' => '¡Comparten el 98% de nuestro ADN!', 'image' => 'https://images.unsplash.com/photo-1742729322173-19b4ed114ac2?w=500'],
            ['zone_id' => 5, 'common_name' => 'Mono capuchino', 'species' => 'Cebus', 'birth_date' => '2019-01-25', 'diet' => 'Omnívoro', 'curiosity' => 'Utiliza su cola como quinta mano para columpiarse.', 'image' => 'https://images.unsplash.com/photo-1721329501836-5e7e2d055f64?w=500'],
            ['zone_id' => 5, 'common_name' => 'Perezoso de tres dedos', 'species' => 'Bradypus tridactylus', 'birth_date' => '2016-12-02', 'diet' => 'Herbívoro', 'curiosity' => 'Son tan lentos que algas verdes crecen en su pelaje.', 'image' => 'https://images.unsplash.com/photo-1520601323386-09e414c5b3ab?w=500'],
            ['zone_id' => 5, 'common_name' => 'Jaguar', 'species' => 'Panthera onca', 'birth_date' => '2018-09-14', 'diet' => 'Carnívoro', 'curiosity' => 'A los jaguares les encanta el agua y cazan incluso bajo el agua.', 'image' => 'https://images.unsplash.com/photo-1542301072-7bc0931d87e1?w=500'],
            ['zone_id' => 5, 'common_name' => 'Gorila de costa', 'species' => 'Gorilla gorilla', 'birth_date' => '2013-05-18', 'diet' => 'Herbívoro', 'curiosity' => 'Viven liderados por un macho dominante conocido como espalda plateada.', 'image' => 'https://images.unsplash.com/photo-1541604085429-191834169736?w=500'],
            ['zone_id' => 5, 'common_name' => 'Lémur de cola anillada', 'species' => 'Lemur catta', 'birth_date' => '2020-02-28', 'diet' => 'Omnívoro', 'curiosity' => 'Pelean usando guerras de olores.', 'image' => 'https://images.unsplash.com/photo-1535565551936-e8d1ee7d83dd?w=500'],
            ['zone_id' => 5, 'common_name' => 'Tigre de Bengala', 'species' => 'Panthera tigris tigris', 'birth_date' => '2017-08-08', 'diet' => 'Carnívoro', 'curiosity' => 'El patrón de rayas de cada tigre es único.', 'image' => 'https://images.unsplash.com/photo-1503066211613-c17ebc9daef0?w=500'],
            ['zone_id' => 5, 'common_name' => 'Orangután de Borneo', 'species' => 'Pongo pygmaeus', 'birth_date' => '2012-05-14', 'diet' => 'Frugívoro', 'curiosity' => 'Son los animales arborícolas más grandes del mundo.', 'image' => 'https://images.unsplash.com/photo-1548674998-c11fbde2ec14?w=500'],
            ['zone_id' => 5, 'common_name' => 'Pantera Negra', 'species' => 'Panthera pardus', 'birth_date' => '2016-10-09', 'diet' => 'Carnívoro', 'curiosity' => 'Si la miras al sol, se ven sus manchas.', 'image' => 'https://images.unsplash.com/photo-1517649281203-cb8ec944f243?w=500'],
            ['zone_id' => 5, 'common_name' => 'Tapir Amazónico', 'species' => 'Tapirus terrestris', 'birth_date' => '2017-08-30', 'diet' => 'Herbívoro', 'curiosity' => 'Usan su hocico como snorkel.', 'image' => 'https://images.unsplash.com/photo-1621578144222-19e07fb8d3c1?w=500'],
            ['zone_id' => 5, 'common_name' => 'Águila Harpía', 'species' => 'Harpia harpyja', 'birth_date' => '2014-11-11', 'diet' => 'Carnívoro', 'curiosity' => 'Sus garras son más grandes que las de un oso pardo.', 'image' => 'https://images.unsplash.com/photo-1601002242055-3ee8b1b22e4c?w=500'],
            ['zone_id' => 5, 'common_name' => 'Tití Leoncito', 'species' => 'Cebuella pygmaea', 'birth_date' => '2023-03-01', 'diet' => 'Omnívoro', 'curiosity' => 'Un adulto cabe perfectamente en la palma de una mano humana.', 'image' => 'https://images.unsplash.com/photo-1534062630776-6330ce148281?w=500'],
        ];

        foreach ($animals as $animal) {
            Animal::create($animal);
        }
    }
}
